os:
- linux
language: node_js
node_js:
- 14
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key: 11253934-1940-410d-bee0-b4e13abf6f6a
  app: o2seeker
  on:
    repo: schwarzkartoffel/O2Seeker
env:
  global:
    secure: j15rkcQvZRv6O6hf+4xSAwE75pz6pETRCfy4uhLE2Y6N+kc38p+A2MNZNn8UzVagjo5lh8tIfL/fDWcHxtv6HzSr7RpvzT0lu5DO+aLVz+mV8pUXxIMR+aWz95RDqSaBE+K2FG2g78OYyS6DhX7mBVIFv2Vtc2x0e99IYgZBbQSfWsDNKRpC/JNnFslwwyHl46R3ZQyk9vbZngxN4kdueWMTzGY/CLC3k4peeJH/JoDZIHk1iyyrROTicbB2pJIETLR0sxfQeLkPYFhCyjIkVwZ9YQ5O8rQZ3n7hz442TUHPfdFd3rynbipuk5xtKqehDNdV5DjpOo+4n2hK0CQY01wY2LhVvIcoEj2+w7xv7qAb2+zofpT1y37DDzZCjX6EemYMQ+LqRCBH7vprDe/qfIj7U1uZwsFtG+IyU5wh4Seke1Iab2p/9cg+4KmiP0AiGPCYQOVmruQWaoEUAhY+ecGQ3PxgRocFtMOZAbtOLFfSVfM4KosJ7B6WzKRS36YH1rI8aTkWdSJN9tDkED/8x8uwpUe/Ey1Mt7btAvjfl5Ufb6VE6JpA7ec26/V/tTNNAvAXjVwX9MVALsrs24vLzYDxlScwdCFb4JeXDGyrp/wR3mryKUH72+aTTsgHdRoQak5j68fBgM4jbZdiCzRMldB5JeELFYZvceI7RPdhQSc=
