os:
- linux
language: node_js
node_js:
- 14
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: o2seeker
  on:
    repo: schwarzkartoffel/O2Seeker
env:
  global:
    secure: Vr+wK/bQnI6tuiO/VSy0uwONS5B1DeeiHIJhhzqSgteJbT3djM3mWgCIVFJrmVz9BdPdegOrpBWFyuPi1NhMrqFWIMGKH6b1fH3jneZ8qWVjJu4D+YBos/4DKhLzgrYnC6Tip1sE1UmVVpQfuex3LGiiseCD+AcdqvN4Gc15w5rLqsWTPKU5Zh9xW1rRlZAJ6Ms6REhSWJHJnDfoPZaOMB1Gy85UnOZoqfVN5uWdflW6r7ueDGI56kRQ0fD8uQWYnUoQ22xzl74adD8gJKy2IklkuuIZSVOKJG5I79ej4SPktx1NGyz7bC1dzyRawgpj1gAH3FCnXKZEUN5/VQ/uZfI75Ktx7N0sev8pYaNP16Lve2iyIFrKvz/ISiVqQG22UNs+JqbSISeUNl0ddDYE9ePrjZOJ3ancu9vPiffBsBcZB6DSUvl6QUPuBZndHeh3Ek4ils8yNWrJX5XsKLRA+4qvcRZ6NOqf4mX52VoBXSc7E92PofbBcqBStPDopOV3afjRbluqm7fQcAW4ytaZcsuICYVbnC7uqszWB9fyKrLIAj3U5+Gksp1zuLKXF97e9/KD89GY06pTa1xEzlBiRVDBBZu5DiOO4aOQK06Yi1mPBx4bJhRiL8B0I/90npzWSivhqdFabQkmr7B9rg3pyq7t6bctKrqrB71v+SYsjLk=
